version: '2'

volumes:
  settings:                          # Only required if using PERSISTANT flag (see below)

services:

  browser:
    image: balenablocks/browser:raspberrypi4-64
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    volumes:
      - 'settings:/data' # Only required if using PERSISTANT flag (see below)